name: 'clima_latam'
version: '1.0.0'
config-version: 2

profile: 'clima_latam'

model-paths: ["models"]
test-paths: ["tests"]
docs-paths: ["docs"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  clima_latam:
    staging:
      +materialized: view
      +schema: weather_clean
    marts:
      +materialized: table
      +schema: weather_mart
